WIP: sync/rate: implements golang-like rate limiter
moonlibs/sync pull request #7
Opened 2023-05-15 22:13 UTC by ochaton

## Description
- sync/rate implements TokenBucket rate limiter
- client may create rate limiter with passing `limit` and `burst`
- rate limiter can have at most `burst` tokens
- rate limiter is refilled with token at rate `limit` tokens per second (can be fractional)
- ratelimit exposes 3 public methods:

	- `rate:wait([timeout=now, [n=1]])` awaits for `n` tokens within `timeout` seconds (can be fractional)
	- `rate:reserve([timestamp=now(), [n=1]])` creates reservation for `n` tokens which will be consumed at `timestamp` (non expired reservations can be cancelled)
	- `rate:allow([timestamp=now(), [n=1]])` auto reserves `n` token to be consumed at time `timestamp` (don't think someone need this method at all)

rate limiter implements TokenBucket with infinite `limit` (must set math.huge for limit). That means, that consumer is always allowed to fetch `n` tokens from rate limiter.

rate limiter implements fixed Token Bucket (without refilling) when `limit=0`. Then consumers are allowed to fetch at most `burst` tokens from rate limiter, after that rate limiter is drained and no one allowed to fetch tokens from it.

## Next Steps

- [ ] Unit Tests
- [ ] Update readme with some examples

2023-05-15 22:17 UTC, ochaton commented on sync/rate.lua
> +	if name == limit then error("Usage: limit.new([name]) or limit([name]) (not limit:new())", 2) end
fix indentations

2023-05-15 22:17 UTC, ochaton commented on sync/rate.lua
> +return limit
add newline

2023-05-15 22:17 UTC, ochaton commented on sync/rate.lua
> +    --- think about this:
provide testcase

2023-05-15 22:18 UTC, ochaton commented on sync/rate.lua
> +limit.__tostring = function (self) return "limit<".. (self.name or 'anon') ..">" end
module name? limit -> rate

2023-06-05 09:46 UTC, Mons requested changes

2023-06-05 09:46 UTC, Mons commented on sync/rate.lua
> +    if name == rate then error("Usage: rate.new([name]) or limit([name]) (not limit:new())", 2) end
possible should be

```
error("Usage: rate.new(name, [rps, burst]) or rate(name, [rps, burst]) (not rate:new(...))", 2)
```

2023-06-05 09:46 UTC, Mons commented on sync/rate.lua
> +    if rps < 0 then error("Usage: rate.new([name], rps, burst) rps must be non negative", 2) end
Consider the same usage message here. name is not optional

2023-06-05 09:46 UTC, Mons commented on sync/rate.lua
> +---Can return `math.huge` is limit is non-positive
---Can return `math.huge` _if_ limit is non-positive

2023-06-05 09:46 UTC, Mons commented on sync/rate.lua
> +        return false, ("limit:wait(timeout=%s, n=%s) exceeds limiters burst=%s"):format(timeout, n, self.burst)
limit or rate?

2023-06-05 09:46 UTC, Mons commented on sync/rate.lua
> +        return false, ("limit:wait(timeout=%s, n=%s) %s"):format(timeout, n, err)
limit or rate?

2023-06-05 14:56 UTC, ochaton commented on sync/rate.lua
> +    if name == rate then error("Usage: rate.new([name]) or limit([name]) (not limit:new())", 2) end
fixed

2023-06-05 14:56 UTC, ochaton commented on sync/rate.lua
> +    if rps < 0 then error("Usage: rate.new([name], rps, burst) rps must be non negative", 2) end
fixed

2023-06-05 14:56 UTC, ochaton commented on sync/rate.lua
> +        return false, ("limit:wait(timeout=%s, n=%s) exceeds limiters burst=%s"):format(timeout, n, self.burst)
fixed

2023-06-05 14:56 UTC, ochaton commented on sync/rate.lua
> +        return false, ("limit:wait(timeout=%s, n=%s) %s"):format(timeout, n, err)
fixed, now `rate`

2023-06-08 09:07 UTC, merged